### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by olibre** [joboccara/NamedType#2]
1. Add a file LICENSE containing your license text.
2. Mention your license within your README.md.
3. Append a short license banner on top of each of your source code file.

Provide a different license for your code source and documentation.
Your code source could be licensed using MIT or GPL,
and your documentation using CC-BY-SA.

Thanks for your talk at C++FRUG Paris ;)

**Comment by hpenne** [comment]
This has my vote as well.  Personally, I'd prefer the MIT license to GLP as it is more permissive.

It seems that the code cannot be legally used by others without a license, we're only allowed to read it.  This covers the issue in some detail: http://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html

Which is too bad, because this code is really useful.

**Comment by olibre** [comment]
Licence has been added 😀   
https://github.com/joboccara/NamedType/blob/master/LICENSE

**Comment by mropert** [comment]
I think you forgot to input your name & date :)

**Comment by joboccara** [comment]
The license now has a name and date, so I'm closing the issue if it's ok with you.
